[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "frontend/build"

[functions]
  directory = "frontend/functions"

[[redirects]]
  force = true
  front = /"loquesea"
  status = 200
  to = "https://tfg-ndno.onrender.com/api/auth/signin"